### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by antuki** [antuki/RR2023_tuto_statspatiale#1]
**Pense-bête Kim pour prochain point oral**
- [ ] Demander à comeetie l'explication de la phrase de lecture _"sf utilise la géométrie sphérique par défaut pour les données non projetées depuis la version 1.0 grâce à la librairie s2"._
- [ ] Demander à comeetie l'explication de la phrase de lecture _"Le format gpkg (geopackage) est ouvert (non lié à un système d’exploitation) et implémenté sous la forme d’une base de données SQLite."_
- [ ] Montrer à comeetie le `lecture-slide.html`
